/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.33
 * Generated at: 2017-03-04 08:29:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("/WEB-INF/views/header.jsp", Long.valueOf(1488615709688L));
    _jspx_dependants.put("/WEB-INF/views/footer.jsp", Long.valueOf(1487653772716L));
    _jspx_dependants.put("jar:file:/C:/mywork/savvydude.com/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/savvydude/WEB-INF/lib/spring-security-taglibs-4.2.1.RELEASE.jar!/META-INF/security.tld", Long.valueOf(1482320444000L));
    _jspx_dependants.put("jar:file:/C:/mywork/savvydude.com/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/savvydude/WEB-INF/lib/standard-1.1.2.jar!/META-INF/c.tld", Long.valueOf(1098691290000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-security-taglibs-4.2.1.RELEASE.jar", Long.valueOf(1488609620432L));
    _jspx_dependants.put("/WEB-INF/lib/standard-1.1.2.jar", Long.valueOf(1487570099721L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write(' ');
      out.write(' ');
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Montserrat\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("<title>HOME-savvydude</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"Resources/css/header.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"container-fluid\" style=\"margin-left:0px; margin-top:0px; margin-right:0px; background-color:#C5C5C5\">\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("<div class=\"col-lg-4\">\r\n");
      out.write("<img class=\"img-responsive \" src=\"Resources/images/logo.png\" alt=\"logo\" style=\"width:50%; height:140px;\">\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"col-lg-8\" >\r\n");
      out.write("<img class=\"img-responsive\" src=\"Resources/images/banner2.png\" alt=\"banner\" style=\"width:130%; height:140px;\">\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"navbar navbar-default \" role=\"navigation\">\r\n");
      out.write("    <div class=\"container-fluid\">\r\n");
      out.write("        <div class=\"navbar-header\">\r\n");
      out.write("            <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\".navbar-collapse\">\r\n");
      out.write("                <span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("                <span class=\"icon-bar\"></span>\r\n");
      out.write("                <span class=\"icon-bar\"></span>\r\n");
      out.write("                <span class=\"icon-bar\"></span>\r\n");
      out.write("            </button>\r\n");
      out.write("            <a class=\"navbar-brand\" href=\"#\">savvydude</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"collapse navbar-collapse\">\r\n");
      out.write("<ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("        ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("        ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("        ");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("        <li><a href=\"#\"><span class=\"glyphicon glyphicon-shopping-cart\"></span>    Shopping Cart:0</a></li>\r\n");
      out.write("       </ul>\r\n");
      out.write("            <ul class=\"nav navbar-nav\">\r\n");
      out.write("                <li class=\"active\"><a href=\"home\">Home</a></li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\"> Categories <b class=\"caret\"></b></a>\r\n");
      out.write("                    <ul class=\"dropdown-menu multi-level\">\r\n");
      out.write("                        <li class=\"dropdown-submenu\">\r\n");
      out.write("                            <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">Companies</a>\r\n");
      out.write("                            <ul class=\"dropdown-menu\">\r\n");
      out.write("                                 <li class=\"dropdown-submenu\">\r\n");
      out.write("                                    <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">Apple</a>\r\n");
      out.write("                                    <ul class=\"dropdown-menu\">\r\n");
      out.write("                                    <li><a href=\"#\">iWatch</a></li>\r\n");
      out.write("                                    <li><a href=\"#\">iPod</a></li>\r\n");
      out.write("                                    <li><a href=\"#\">iMac</a></li>\r\n");
      out.write("                                    <li><a href=\"#\">iPad</a></li>\r\n");
      out.write("                                        <li class=\"dropdown-submenu\">\r\n");
      out.write("                                            <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">iPhones</a>\r\n");
      out.write("                                                 <ul class=\"dropdown-menu\">\r\n");
      out.write("                                                <li><a href=\"#\">iPhone 5s</a></li>\r\n");
      out.write("                                                <li><a href=\"#\">iPhone 6 </a></li>\r\n");
      out.write("                                                <li><a href=\"#\">iPhone 6s</a></li>\r\n");
      out.write("                                                <li><a href=\"#\">iPhone 6s Plus</a></li>\r\n");
      out.write("                                                <li><a href=\"#\">iPhone 5se</a></li>\r\n");
      out.write("                                                <li><a href=\"#\">iPhone 7</a></li>\r\n");
      out.write("                                                <li><a href=\"#\">iPhone 7 Plus</a></li>\r\n");
      out.write("                                            </ul>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                    \r\n");
      out.write("                                     <li class=\"dropdown-submenu\">\r\n");
      out.write("                                     <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\"> Samsung </a>\r\n");
      out.write("\t\t\t\t\t\t\t\t     <ul class=\"dropdown-menu\">\t\t\t\t\t\t\t\t    \r\n");
      out.write("\t\t\t\t\t\t\t\t    <li class=\"dropdown-submenu\">\r\n");
      out.write("                                            <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">Phones</a>\r\n");
      out.write("                                                 <ul class=\"dropdown-menu\">\r\n");
      out.write("                                                 <li class=\"dropdown-submenu\">\r\n");
      out.write("                                            <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">Galaxy J</a>\r\n");
      out.write("                                             <ul class=\"dropdown-menu\">\r\n");
      out.write("                                               <li><a href=\"#\">Galaxy J2</a></li>\r\n");
      out.write("                                              <li><a href=\"#\">Galaxy J5</a></li>\r\n");
      out.write("                                              <li><a href=\"#\">Galaxy J7</a></li>\r\n");
      out.write("                                              </ul></li>\r\n");
      out.write("                                        <li class=\"dropdown-submenu\">\r\n");
      out.write("                                            <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">Galaxy Note</a>\r\n");
      out.write("                                            <ul class=\"dropdown-menu\">\r\n");
      out.write("                                            <li><a href=\"#\">Galaxy Note 3</a></li>\r\n");
      out.write("                                            <li><a href=\"#\">Galaxy Note 4</a></li>\r\n");
      out.write("                                            <li><a href=\"#\">Galaxy Note 5</a></li>\r\n");
      out.write("                                            </ul>\r\n");
      out.write("                                            </li>\r\n");
      out.write("                                              <li class=\"dropdown-submenu\">\r\n");
      out.write("                                            <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">Galaxy S</a>\r\n");
      out.write("                                            <ul class=\"dropdown-menu\">\r\n");
      out.write("                                            <li><a href=\"#\">Galaxy S4</a></li>\r\n");
      out.write("                                            <li><a href=\"#\">Galaxy S5</a></li>\r\n");
      out.write("                                            <li><a href=\"#\">Galaxy S5</a></li>\r\n");
      out.write("                                            <li><a href=\"#\">Galaxy S6 Edge</a></li>\r\n");
      out.write("                                            <li><a href=\"#\">Galaxy S7 Edge</a></li>\r\n");
      out.write("                                            </ul>\r\n");
      out.write("                                            </li>\r\n");
      out.write("                                            </ul>\r\n");
      out.write("                                       <li class=\"dropdown-submenu\">\r\n");
      out.write("                                            <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">Smart Watches</a>\r\n");
      out.write("                                          <ul class=\"dropdown-menu\">\r\n");
      out.write("                                            <li><a href=\"#\"> Samsung Gear 2</a></li>\r\n");
      out.write("                                       </ul>\r\n");
      out.write("                                    </li>\t</ul>\r\n");
      out.write("                                    <li class=\"dropdown-submenu\">\r\n");
      out.write("                                     <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\"> One Plus </a>\r\n");
      out.write("                                       <ul class=\"dropdown-menu\">\t\t\t\t\t\t\t\t    \r\n");
      out.write("\t\t\t\t\t\t\t\t    <li class=\"dropdown-submenu\">\r\n");
      out.write("                                            <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">Phones</a>\r\n");
      out.write("                                                 <ul class=\"dropdown-menu\">\r\n");
      out.write("                                                 <li><a href=\"#\">OnePlus 2</a></li>\r\n");
      out.write("                                                 <li><a href=\"#\">OnePlus 3</a></li>\r\n");
      out.write("                                                 </ul></li></ul>                                   \t\t\t\t\t\t\t\t    \r\n");
      out.write("                                    </li></ul></li>\r\n");
      out.write("                           <li class=\"dropdown-submenu\">\r\n");
      out.write("                                <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">Operating System</a>\r\n");
      out.write("                           <ul class=\"dropdown-menu\">\r\n");
      out.write("                                    <li><a href=\"#\">iOS  </a></li>\r\n");
      out.write("                                    <li><a href=\"#\">Android </a></li>\r\n");
      out.write("                                    <li><a href=\"#\">Windows </a></li>\r\n");
      out.write("                               </ul></li>   \t\t                                    \r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                                   \r\n");
      out.write("                <li>   <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\"> Products <b class=\"caret\"></b></a>\r\n");
      out.write("                    <ul class=\"dropdown-menu\">\r\n");
      out.write("                        <li><a href=\"#\">Phones</a></li>\r\n");
      out.write("                        <li class=\"divider\"></li>\r\n");
      out.write("                        <li><a href=\"#\">Smart Watches</a></li>\r\n");
      out.write("                        <li class=\"divider\"></li>\r\n");
      out.write("                        <li><a href=\"#\">iPods</a></li>\r\n");
      out.write("                        <li class=\"divider\"></li>\r\n");
      out.write("                        <li><a href=\"#\">Desktops</a></li>\r\n");
      out.write("                        \r\n");
      out.write("                           </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("           </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("    <div class=\"container\">    \r\n");
      out.write("        <div id=\"loginbox\" style=\"margin-top:50px;\" class=\"mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2\">                    \r\n");
      out.write("            <div class=\"panel panel-info\" >\r\n");
      out.write("                    <div class=\"panel-heading\">\r\n");
      out.write("                        <div class=\"panel-title\">Sign In</div>\r\n");
      out.write("                        <div style=\"float:right; font-size: 80%; position: relative; top:-10px\"><a href=\"#\">Forgot password?</a></div>\r\n");
      out.write("                    </div>     \r\n");
      out.write("\r\n");
      out.write("                    <div style=\"padding-top:30px\" class=\"panel-body\" >\r\n");
      out.write("\r\n");
      out.write("                        <div style=\"display:none\" id=\"login-alert\" class=\"alert alert-danger col-sm-12\"></div>\r\n");
      out.write("                         ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${error }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("                            ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${logout }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("                            ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${registrationSuccess }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("                        <form method=\"post\" action=\"");
      if (_jspx_meth_c_005furl_005f2(_jspx_page_context))
        return;
      out.write("\" name=\"loginform\" class=\"form-horizontal\" role=\"form\">\r\n");
      out.write(" \r\n");
      out.write("                                        <div style=\"margin-bottom: 25px\" class=\"input-group\">\r\n");
      out.write("                                        <span class=\"input-group-addon\"><i class=\"glyphicon glyphicon-user\"></i></span>\r\n");
      out.write("                                        <input id=\"login-username\" type=\"text\" class=\"form-control\" name=\"username\" value=\"\" placeholder=\"username or email\">                                        \r\n");
      out.write("                                    </div>\r\n");
      out.write("                                \r\n");
      out.write("                            <div style=\"margin-bottom: 25px\" class=\"input-group\">\r\n");
      out.write("                                        <span class=\"input-group-addon\"><i class=\"glyphicon glyphicon-lock\"></i></span>\r\n");
      out.write("                                        <input id=\"login-password\" type=\"password\" class=\"form-control\" name=\"password\" placeholder=\"password\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    \r\n");
      out.write("\r\n");
      out.write("                                \r\n");
      out.write("                            <div class=\"input-group\">\r\n");
      out.write("                                      <div class=\"checkbox\">\r\n");
      out.write("                                        <label>\r\n");
      out.write("                                          <input id=\"login-remember\" type=\"checkbox\" name=\"remember\" value=\"1\"> Remember me\r\n");
      out.write("                                        </label>\r\n");
      out.write("                                      </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                <div style=\"margin-top:10px\" class=\"form-group\">\r\n");
      out.write("                                    <!-- Button -->\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"col-sm-12 controls\">\r\n");
      out.write("                                      <a id=\"btn-login\" href=\"#\" class=\"btn btn-success\">Login  </a>\r\n");
      out.write("                                      <a id=\"btn-fblogin\" href=\"#\" class=\"btn btn-primary\">Login with Facebook</a>\r\n");
      out.write("\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"form-group\">\r\n");
      out.write("                                    <div class=\"col-md-12 control\">\r\n");
      out.write("                                        <div style=\"border-top: 1px solid#888; padding-top:15px; font-size:85%\" >\r\n");
      out.write("                                            Don't have an account! \r\n");
      out.write("                                        <a href=\"#\" onClick=\"$('#loginbox').hide(); $('#signupbox').show()\">\r\n");
      out.write("                                            Sign Up Here\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>    \r\n");
      out.write("                            </form>     \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        </div>                     \r\n");
      out.write("                    </div>  \r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"signupbox\" style=\"display:none; margin-top:50px\" class=\"mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2\">\r\n");
      out.write("                    <div class=\"panel panel-info\">\r\n");
      out.write("                        <div class=\"panel-heading\">\r\n");
      out.write("                            <div class=\"panel-title\">Sign Up</div>\r\n");
      out.write("                            <div style=\"float:right; font-size: 85%; position: relative; top:-10px\"><a id=\"signinlink\" href=\"#\" onclick=\"$('#signupbox').hide(); $('#loginbox').show()\">Sign In</a></div>\r\n");
      out.write("                        </div>  \r\n");
      out.write("                        <div class=\"panel-body\" >\r\n");
      out.write("                            <form id=\"signupform\" class=\"form-horizontal\" role=\"form\">\r\n");
      out.write("                                \r\n");
      out.write("                                <div id=\"signupalert\" style=\"display:none\" class=\"alert alert-danger\">\r\n");
      out.write("                                    <p>Error:</p>\r\n");
      out.write("                                    <span></span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                    \r\n");
      out.write("                                \r\n");
      out.write("                                  \r\n");
      out.write("                                <div class=\"form-group\">\r\n");
      out.write("                                    <label for=\"email\" class=\"col-md-3 control-label\">Email</label>\r\n");
      out.write("                                    <div class=\"col-md-9\">\r\n");
      out.write("                                        <input type=\"text\" class=\"form-control\" name=\"email\" placeholder=\"Email Address\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                    \r\n");
      out.write("                                <div class=\"form-group\">\r\n");
      out.write("                                    <label for=\"firstname\" class=\"col-md-3 control-label\">First Name</label>\r\n");
      out.write("                                    <div class=\"col-md-9\">\r\n");
      out.write("                                        <input type=\"text\" class=\"form-control\" name=\"firstname\" placeholder=\"First Name\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"form-group\">\r\n");
      out.write("                                    <label for=\"lastname\" class=\"col-md-3 control-label\">Last Name</label>\r\n");
      out.write("                                    <div class=\"col-md-9\">\r\n");
      out.write("                                        <input type=\"text\" class=\"form-control\" name=\"lastname\" placeholder=\"Last Name\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"form-group\">\r\n");
      out.write("                                    <label for=\"password\" class=\"col-md-3 control-label\">Password</label>\r\n");
      out.write("                                    <div class=\"col-md-9\">\r\n");
      out.write("                                        <input type=\"password\" class=\"form-control\" name=\"passwd\" placeholder=\"Password\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                    \r\n");
      out.write("                                <div class=\"form-group\">\r\n");
      out.write("                                    <label for=\"icode\" class=\"col-md-3 control-label\">Invitation Code</label>\r\n");
      out.write("                                    <div class=\"col-md-9\">\r\n");
      out.write("                                        <input type=\"text\" class=\"form-control\" name=\"icode\" placeholder=\"\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"form-group\">\r\n");
      out.write("                                    <!-- Button -->                                        \r\n");
      out.write("                                    <div class=\"col-md-offset-3 col-md-9\">\r\n");
      out.write("                                        <button id=\"btn-signup\" type=\"button\" class=\"btn btn-info\"><i class=\"icon-hand-right\"></i> &nbsp Sign Up</button>\r\n");
      out.write("                                        <span style=\"margin-left:8px;\">or</span>  \r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                \r\n");
      out.write("                                <div style=\"border-top: 1px solid #999; padding-top:20px\"  class=\"form-group\">\r\n");
      out.write("                                    \r\n");
      out.write("                                    <div class=\"col-md-offset-3 col-md-9\">\r\n");
      out.write("                                        <button id=\"btn-fbsignup\" type=\"button\" class=\"btn btn-primary\"><i class=\"icon-facebook\"></i>   Sign Up with Facebook</button>\r\n");
      out.write("                                    </div>                                           \r\n");
      out.write("                                        \r\n");
      out.write("                                </div>\r\n");
      out.write("                                \r\n");
      out.write("                                \r\n");
      out.write("                                \r\n");
      out.write("                            </form>\r\n");
      out.write("                         </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("               \r\n");
      out.write("               \r\n");
      out.write("                \r\n");
      out.write("         </div> \r\n");
      out.write("    </div>\r\n");
      out.write("    ");
      out.write("<link rel=\"stylesheet\" href=\"Resources/css/footer.css\">\r\n");
      out.write("<div class=\"container-fluid\">\r\n");
      out.write("    <section style=\"height:80px;\"></section>\r\n");
      out.write("\t<div class=\"row\" style=\"text-align:center;\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("    <footer class=\"footer-bs\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("        \t<div class=\"col-md-3 footer-brand animated fadeInLeft\">\r\n");
      out.write("   \t\t\t     \t\r\n");
      out.write("            </div>\r\n");
      out.write("        \t<div class=\"col-md-4 footer-nav animated fadeInUp\">\r\n");
      out.write("            \t<h4>Menu</h4>\r\n");
      out.write("            \t<div class=\"col-md-6\">\r\n");
      out.write("                    <ul class=\"pages\">\r\n");
      out.write("                        <li><a href=\"#\">Travel</a></li>\r\n");
      out.write("                        <li><a href=\"#\">Nature</a></li>\r\n");
      out.write("                        <li><a href=\"#\">Explores</a></li>\r\n");
      out.write("                        <li><a href=\"#\">Science</a></li>\r\n");
      out.write("                        <li><a href=\"#\">Advice</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            \t<div class=\"col-md-6\">\r\n");
      out.write("                    <ul class=\"list\">\r\n");
      out.write("                        <li><a href=\"aboutus\">About Us</a></li>\r\n");
      out.write("                        <li><a href=\"contactus.jsp\">Contact Us</a></li>\r\n");
      out.write("                        <li><a href=\"#\">Terms & Condition</a></li>\r\n");
      out.write("                        <li><a href=\"#\">Privacy Policy</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        \t<div class=\"col-md-2 footer-social animated fadeInDown\">\r\n");
      out.write("            \t<h4>Follow Us</h4>\r\n");
      out.write("            \t<ul>\r\n");
      out.write("                \t<li><a href=\"#\">Facebook</a></li>\r\n");
      out.write("                \t<li><a href=\"#\">Twitter</a></li>\r\n");
      out.write("                \t<li><a href=\"#\">Instagram</a></li>\r\n");
      out.write("                \t<li><a href=\"#\">RSS</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        \t<div class=\"col-md-3 footer-ns animated fadeInRight\">\r\n");
      out.write("            \t<h4>Newsletter</h4>\r\n");
      out.write("\r\n");
      out.write("                <p>\r\n");
      out.write("                    <div class=\"input-group\">\r\n");
      out.write("                      <input type=\"text\" class=\"form-control\" placeholder=\"Search for...\">\r\n");
      out.write("                      <span class=\"input-group-btn\">\r\n");
      out.write("                        <button class=\"btn btn-default\" type=\"button\"><span class=\"glyphicon glyphicon-envelope\"></span></button>\r\n");
      out.write("                      </span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                 </p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /WEB-INF/views/header.jsp(42,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.userPrincipal.name !=null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("        <li><a href=\"\">Welcome! ");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.userPrincipal.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("</a></li>\r\n");
        out.write("       ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent(null);
    // /WEB-INF/views/header.jsp(45,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.userPrincipal.name ==null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t    <li><a href=\"");
        if (_jspx_meth_c_005furl_005f0(_jspx_th_c_005fif_005f1, _jspx_page_context))
          return true;
        out.write("\"><span class=\"glyphicon glyphicon-pencil\"></span>    Register</a></li>\r\n");
        out.write("        <li><a href=\"login\"><span class=\"glyphicon glyphicon-log-in\"></span>    Login</a></li>\r\n");
        out.write("        ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
    // /WEB-INF/views/header.jsp(46,18) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f0.setValue("/register");
    int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
    if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f2.setParent(null);
    // /WEB-INF/views/header.jsp(49,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.userPrincipal.name !=null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
    if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t<li><a href=\"");
        if (_jspx_meth_c_005furl_005f1(_jspx_th_c_005fif_005f2, _jspx_page_context))
          return true;
        out.write("\"><span class=\"glyphicon glyphicon-log-out\"></span>   Logout</a></li>\r\n");
        out.write("\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f2);
    // /WEB-INF/views/header.jsp(50,16) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f1.setValue("/j_spring_security_logout");
    int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
    if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f2.setParent(null);
    // /WEB-INF/views/login.jsp(16,52) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f2.setValue("/j_spring_security_check");
    int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
    if (_jspx_th_c_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
    return false;
  }
}
