/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.33
 * Generated at: 2017-03-03 06:15:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class signup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/header.jsp", Long.valueOf(1487308564669L));
    _jspx_dependants.put("/WEB-INF/views/footer.jsp", Long.valueOf(1487653772716L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Montserrat\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("<title>HOME-savvydude</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"Resources/css/header.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"container-fluid\" style=\"margin-left:0px; margin-top:0px; margin-right:0px; background-color:#C5C5C5\">\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("<div class=\"col-lg-4\">\r\n");
      out.write("<img class=\"img-responsive \" src=\"Resources/images/logo.png\" alt=\"logo\" style=\"width:50%; height:140px;\">\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"col-lg-8\" >\r\n");
      out.write("<img class=\"img-responsive\" src=\"Resources/images/banner2.png\" alt=\"banner\" style=\"width:130%; height:140px;\">\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"navbar navbar-default \" role=\"navigation\">\r\n");
      out.write("    <div class=\"container-fluid\">\r\n");
      out.write("        <div class=\"navbar-header\">\r\n");
      out.write("            <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\".navbar-collapse\">\r\n");
      out.write("                <span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("                <span class=\"icon-bar\"></span>\r\n");
      out.write("                <span class=\"icon-bar\"></span>\r\n");
      out.write("                <span class=\"icon-bar\"></span>\r\n");
      out.write("            </button>\r\n");
      out.write("            <a class=\"navbar-brand\" href=\"#\">savvydude</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"collapse navbar-collapse\">\r\n");
      out.write("            <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("                <li><a href=\"login\">Login</a></li>\r\n");
      out.write("                <li><a href=\"signup\">Sign Up</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul class=\"nav navbar-nav\">\r\n");
      out.write("                <li class=\"active\"><a href=\"home\">Home</a></li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\"> Categories <b class=\"caret\"></b></a>\r\n");
      out.write("                    <ul class=\"dropdown-menu multi-level\">\r\n");
      out.write("                        <li class=\"dropdown-submenu\">\r\n");
      out.write("                            <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">Companies</a>\r\n");
      out.write("                            <ul class=\"dropdown-menu\">\r\n");
      out.write("                                 <li class=\"dropdown-submenu\">\r\n");
      out.write("                                    <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">Apple</a>\r\n");
      out.write("                                    <ul class=\"dropdown-menu\">\r\n");
      out.write("                                    <li><a href=\"#\">iWatch</a></li>\r\n");
      out.write("                                    <li><a href=\"#\">iPod</a></li>\r\n");
      out.write("                                    <li><a href=\"#\">iMac</a></li>\r\n");
      out.write("                                    <li><a href=\"#\">iPad</a></li>\r\n");
      out.write("                                        <li class=\"dropdown-submenu\">\r\n");
      out.write("                                            <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">iPhones</a>\r\n");
      out.write("                                                 <ul class=\"dropdown-menu\">\r\n");
      out.write("                                                <li><a href=\"#\">iPhone 5s</a></li>\r\n");
      out.write("                                                <li><a href=\"#\">iPhone 6 </a></li>\r\n");
      out.write("                                                <li><a href=\"#\">iPhone 6s</a></li>\r\n");
      out.write("                                                <li><a href=\"#\">iPhone 6s Plus</a></li>\r\n");
      out.write("                                                <li><a href=\"#\">iPhone 5se</a></li>\r\n");
      out.write("                                                <li><a href=\"#\">iPhone 7</a></li>\r\n");
      out.write("                                                <li><a href=\"#\">iPhone 7 Plus</a></li>\r\n");
      out.write("                                            </ul>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                    \r\n");
      out.write("                                     <li class=\"dropdown-submenu\">\r\n");
      out.write("                                     <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\"> Samsung </a>\r\n");
      out.write("\t\t\t\t\t\t\t\t     <ul class=\"dropdown-menu\">\t\t\t\t\t\t\t\t    \r\n");
      out.write("\t\t\t\t\t\t\t\t    <li class=\"dropdown-submenu\">\r\n");
      out.write("                                            <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">Phones</a>\r\n");
      out.write("                                                 <ul class=\"dropdown-menu\">\r\n");
      out.write("                                                 <li class=\"dropdown-submenu\">\r\n");
      out.write("                                            <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">Galaxy J</a>\r\n");
      out.write("                                             <ul class=\"dropdown-menu\">\r\n");
      out.write("                                               <li><a href=\"#\">Galaxy J2</a></li>\r\n");
      out.write("                                              <li><a href=\"#\">Galaxy J5</a></li>\r\n");
      out.write("                                              <li><a href=\"#\">Galaxy J7</a></li>\r\n");
      out.write("                                              </ul></li>\r\n");
      out.write("                                        <li class=\"dropdown-submenu\">\r\n");
      out.write("                                            <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">Galaxy Note</a>\r\n");
      out.write("                                            <ul class=\"dropdown-menu\">\r\n");
      out.write("                                            <li><a href=\"#\">Galaxy Note 3</a></li>\r\n");
      out.write("                                            <li><a href=\"#\">Galaxy Note 4</a></li>\r\n");
      out.write("                                            <li><a href=\"#\">Galaxy Note 5</a></li>\r\n");
      out.write("                                            </ul>\r\n");
      out.write("                                            </li>\r\n");
      out.write("                                              <li class=\"dropdown-submenu\">\r\n");
      out.write("                                            <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">Galaxy S</a>\r\n");
      out.write("                                            <ul class=\"dropdown-menu\">\r\n");
      out.write("                                            <li><a href=\"#\">Galaxy S4</a></li>\r\n");
      out.write("                                            <li><a href=\"#\">Galaxy S5</a></li>\r\n");
      out.write("                                            <li><a href=\"#\">Galaxy S5</a></li>\r\n");
      out.write("                                            <li><a href=\"#\">Galaxy S6 Edge</a></li>\r\n");
      out.write("                                            <li><a href=\"#\">Galaxy S7 Edge</a></li>\r\n");
      out.write("                                            </ul>\r\n");
      out.write("                                            </li>\r\n");
      out.write("                                            </ul>\r\n");
      out.write("                                       <li class=\"dropdown-submenu\">\r\n");
      out.write("                                            <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">Smart Watches</a>\r\n");
      out.write("                                          <ul class=\"dropdown-menu\">\r\n");
      out.write("                                            <li><a href=\"#\"> Samsung Gear 2</a></li>\r\n");
      out.write("                                       </ul>\r\n");
      out.write("                                    </li>\t</ul>\r\n");
      out.write("                                    <li class=\"dropdown-submenu\">\r\n");
      out.write("                                     <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\"> One Plus </a>\r\n");
      out.write("                                       <ul class=\"dropdown-menu\">\t\t\t\t\t\t\t\t    \r\n");
      out.write("\t\t\t\t\t\t\t\t    <li class=\"dropdown-submenu\">\r\n");
      out.write("                                            <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">Phones</a>\r\n");
      out.write("                                                 <ul class=\"dropdown-menu\">\r\n");
      out.write("                                                 <li><a href=\"#\">OnePlus 2</a></li>\r\n");
      out.write("                                                 <li><a href=\"#\">OnePlus 3</a></li>\r\n");
      out.write("                                                 </ul></li></ul>                                   \t\t\t\t\t\t\t\t    \r\n");
      out.write("                                    </li></ul></li>\r\n");
      out.write("                           <li class=\"dropdown-submenu\">\r\n");
      out.write("                                <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">Operating System</a>\r\n");
      out.write("                           <ul class=\"dropdown-menu\">\r\n");
      out.write("                                    <li><a href=\"#\">iOS  </a></li>\r\n");
      out.write("                                    <li><a href=\"#\">Android </a></li>\r\n");
      out.write("                                    <li><a href=\"#\">Windows </a></li>\r\n");
      out.write("                               </ul></li>   \t\t                                    \r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                                   \r\n");
      out.write("                <li>   <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\"> Products <b class=\"caret\"></b></a>\r\n");
      out.write("                    <ul class=\"dropdown-menu\">\r\n");
      out.write("                        <li><a href=\"#\">Phones</a></li>\r\n");
      out.write("                        <li class=\"divider\"></li>\r\n");
      out.write("                        <li><a href=\"#\">Smart Watches</a></li>\r\n");
      out.write("                        <li class=\"divider\"></li>\r\n");
      out.write("                        <li><a href=\"#\">iPods</a></li>\r\n");
      out.write("                        <li class=\"divider\"></li>\r\n");
      out.write("                        <li><a href=\"#\">Desktops</a></li>\r\n");
      out.write("                        \r\n");
      out.write("                           </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("           </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"Resources/css/signup.css\">\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("    <div class=\"col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3\">\r\n");
      out.write("    \t<form role=\"form\">\r\n");
      out.write("\t\t\t<h2>Sign Up</h2>\r\n");
      out.write("\t\t\t<hr class=\"colorgraph\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-xs-6 col-sm-6 col-md-6\">\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("                        <input type=\"text\" name=\"first_name\" id=\"first_name\" class=\"form-control input-lg\" placeholder=\"First Name\" tabindex=\"1\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-xs-6 col-sm-6 col-md-6\">\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"last_name\" id=\"last_name\" class=\"form-control input-lg\" placeholder=\"Last Name\" tabindex=\"2\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"display_name\" id=\"display_name\" class=\"form-control input-lg\" placeholder=\"Display Name\" tabindex=\"3\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t<input type=\"email\" name=\"email\" id=\"email\" class=\"form-control input-lg\" placeholder=\"Email Address\" tabindex=\"4\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-xs-6 col-sm-6 col-md-6\">\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"password\" name=\"password\" id=\"password\" class=\"form-control input-lg\" placeholder=\"Password\" tabindex=\"5\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-xs-6 col-sm-6 col-md-6\">\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"password\" name=\"password_confirmation\" id=\"password_confirmation\" class=\"form-control input-lg\" placeholder=\"Confirm Password\" tabindex=\"6\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<hr class=\"colorgraph\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-xs-6 col-md-6\"><input type=\"button\" value=\"Register\" class=\"btn btn-primary btn-block btn-lg\" tabindex=\"7\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"col-xs-6 col-md-6\"><a href=\"#\" class=\"btn btn-success btn-block btn-lg\">Sign In</a></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- Modal -->\r\n");
      out.write("<div class=\"modal fade\" id=\"t_and_c_m\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("\t<div class=\"modal-dialog\">\r\n");
      out.write("\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">×</button>\r\n");
      out.write("\t\t\t\t<h4 class=\"modal-title\" id=\"myModalLabel\">Terms & Conditions</h4>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique, itaque, modi, aliquam nostrum at sapiente consequuntur natus odio reiciendis perferendis rem nisi tempore possimus ipsa porro delectus quidem dolorem ad.</p>\r\n");
      out.write("\t\t\t\t<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique, itaque, modi, aliquam nostrum at sapiente consequuntur natus odio reiciendis perferendis rem nisi tempore possimus ipsa porro delectus quidem dolorem ad.</p>\r\n");
      out.write("\t\t\t\t<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique, itaque, modi, aliquam nostrum at sapiente consequuntur natus odio reiciendis perferendis rem nisi tempore possimus ipsa porro delectus quidem dolorem ad.</p>\r\n");
      out.write("\t\t\t\t<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique, itaque, modi, aliquam nostrum at sapiente consequuntur natus odio reiciendis perferendis rem nisi tempore possimus ipsa porro delectus quidem dolorem ad.</p>\r\n");
      out.write("\t\t\t\t<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique, itaque, modi, aliquam nostrum at sapiente consequuntur natus odio reiciendis perferendis rem nisi tempore possimus ipsa porro delectus quidem dolorem ad.</p>\r\n");
      out.write("\t\t\t\t<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique, itaque, modi, aliquam nostrum at sapiente consequuntur natus odio reiciendis perferendis rem nisi tempore possimus ipsa porro delectus quidem dolorem ad.</p>\r\n");
      out.write("\t\t\t\t<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique, itaque, modi, aliquam nostrum at sapiente consequuntur natus odio reiciendis perferendis rem nisi tempore possimus ipsa porro delectus quidem dolorem ad.</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btn btn-primary\" data-dismiss=\"modal\">I Agree</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div><!-- /.modal-content -->\r\n");
      out.write("\t</div><!-- /.modal-dialog -->\r\n");
      out.write("</div><!-- /.modal -->\r\n");
      out.write("</div>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"Resources/css/footer.css\">\r\n");
      out.write("<div class=\"container-fluid\">\r\n");
      out.write("    <section style=\"height:80px;\"></section>\r\n");
      out.write("\t<div class=\"row\" style=\"text-align:center;\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("    <footer class=\"footer-bs\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("        \t<div class=\"col-md-3 footer-brand animated fadeInLeft\">\r\n");
      out.write("   \t\t\t     \t\r\n");
      out.write("            </div>\r\n");
      out.write("        \t<div class=\"col-md-4 footer-nav animated fadeInUp\">\r\n");
      out.write("            \t<h4>Menu</h4>\r\n");
      out.write("            \t<div class=\"col-md-6\">\r\n");
      out.write("                    <ul class=\"pages\">\r\n");
      out.write("                        <li><a href=\"#\">Travel</a></li>\r\n");
      out.write("                        <li><a href=\"#\">Nature</a></li>\r\n");
      out.write("                        <li><a href=\"#\">Explores</a></li>\r\n");
      out.write("                        <li><a href=\"#\">Science</a></li>\r\n");
      out.write("                        <li><a href=\"#\">Advice</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            \t<div class=\"col-md-6\">\r\n");
      out.write("                    <ul class=\"list\">\r\n");
      out.write("                        <li><a href=\"aboutus\">About Us</a></li>\r\n");
      out.write("                        <li><a href=\"contactus.jsp\">Contact Us</a></li>\r\n");
      out.write("                        <li><a href=\"#\">Terms & Condition</a></li>\r\n");
      out.write("                        <li><a href=\"#\">Privacy Policy</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        \t<div class=\"col-md-2 footer-social animated fadeInDown\">\r\n");
      out.write("            \t<h4>Follow Us</h4>\r\n");
      out.write("            \t<ul>\r\n");
      out.write("                \t<li><a href=\"#\">Facebook</a></li>\r\n");
      out.write("                \t<li><a href=\"#\">Twitter</a></li>\r\n");
      out.write("                \t<li><a href=\"#\">Instagram</a></li>\r\n");
      out.write("                \t<li><a href=\"#\">RSS</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        \t<div class=\"col-md-3 footer-ns animated fadeInRight\">\r\n");
      out.write("            \t<h4>Newsletter</h4>\r\n");
      out.write("\r\n");
      out.write("                <p>\r\n");
      out.write("                    <div class=\"input-group\">\r\n");
      out.write("                      <input type=\"text\" class=\"form-control\" placeholder=\"Search for...\">\r\n");
      out.write("                      <span class=\"input-group-btn\">\r\n");
      out.write("                        <button class=\"btn btn-default\" type=\"button\"><span class=\"glyphicon glyphicon-envelope\"></span></button>\r\n");
      out.write("                      </span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                 </p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
